create extension if not exists "uuid-ossp";

create table if not exists products (
	id uuid primary key default uuid_generate_v4(),
	title text not null,
	description text,
	price integer not null CHECK (price > 0)
);

create table if not exists stocks (
    product_id uuid,
    count integer not null CHECK (count >= 0)
);

alter table if exists stocks
    add constraint stocks_product_id_fkey foreign key (product_id)
    references products (id) match simple
    on update no action
    on delete cascade;


insert into products (title, description, price) values
('Product #1', 'Short Product #1 Description', 2.4 ),
('Product #2', 'Short Product #2 Description', 10 ),
('Product #3', 'Short Product #3 Description', 23 ),
('Product #4', 'Short Product #4 Description', 15 ),
('Product #5', 'Short Product #5 Description', 23 ),
('Product #6', 'Short Product #6 Description', 15 ),
('Product #7', 'Short Product #7 Description', 23 ),
('Product #8', 'Short Product #8 Description', 15 );

-- list of product_id from script below has been used as an example,
-- real values will be automatically generated by uuid_generate_v4 at the time of inserting products into products table
insert into stocks (product_id, count) values
('0d308af6-1a39-4600-bc85-af0a9c409cec', 5),
('50b6c3f4-3a91-4cf8-9abb-460f1e283c8b', 10),
('b6c62f4a-1b26-4ca5-9c45-8eb27d130262', 15),
('92486f8e-db59-4629-a1ad-c64e1c4dceac', 20),
('f8160128-1c32-4daf-92a6-a53c5596194a', 5),
('fb52a4b6-c8e5-4fe1-bb02-cd33984c5cd0', 3),
('c98f58a7-cb1b-4cca-97b4-8618525a1419', 10),
('432737ad-dd78-4782-ab06-379aec345be6', 5);










