service: product-service
frameworkVersion: '3'
configValidationMode: error
package:
  individually: true
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
functions:
  getProductsList:
    handler:  src/functions/get-products-list.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
  getProductsById:
    handler: src/functions/get-products-by-id.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get
plugins:
  - serverless-auto-swagger
  - serverless-webpack
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
    excludeFiles: src/**/*.test.js
